services:
  pg-ingest:
    image: taxi_ingest:v1
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=pg-database
      - PORT=5432
      - TABLE_NAME=green_taxi_data
      - URL=https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2019-09.parquet
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    networks:
      - pg-network
    depends_on:
      - pg-database
