services:
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
    networks:
      - pg-network
    depends_on:
      - pg-database
